model: models/gemma-3-270m-it
served-model-name: Marshall-gemma3-270m
enforce-eager: false
gpu-memory-utilization: 0.75
max-seq-len-to-capture: 8192
max-model-len: 8192
max-num-batched-tokens: 8192
seed: 777
enable-prefix-caching: true
disable-log-stats: false
host: "0.0.0.0"
port: 8000
uvicorn-log-level: "info"